export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const UPDATE_COLUMN = "UPDATE_COLUMN";
export const ADD_REQUEST = "ADD_REQUEST";
export const REMOVE_REQUEST = "REMOVE_REQUEST";
export const ADD_REQUEST_DATE = "ADD_REQUEST_DATE";
export const REMOVE_REQUEST_DATE = "REMOVE_REQUEST_DATE";
export const ADD_REQUEST_TIME = "ADD_REQUEST_TIME";
export const REMOVE_REQUEST_TIME = "REMOVE_REQUEST_TIME";

export const ENTITY_USER_LOADED='ENTITY_USER_LOADED';
export const ENTITY_REFERENCES_LOADED='ENTITY_REFERENCES_LOADED';
export const ENTITY_TICKETS_LOADED='ENTITY_TICKETS_LOADED';
export const ENTITY_REQUEST='ENTITY_REQUEST';
export const ENTITY_ALLUSERS_LOADED='ENTITY_ALLUSERS_LOADED';

export const REQUESTED_DOG='REQUESTED_DOG';
export const REQUESTED_DOG_SUCCEEDED='REQUESTED_DOG_SUCCEEDED';
export const REQUESTED_DOG_FAILED='REQUESTED_DOG_FAILED';
export const FETCHED_DOG='FETCHED_DOG';

export const GET_TICKET_ID = `GET_TICKET_ID`;
export const LOAD_COMMENTS = `LOAD_COMMENTS`;
export const LOAD_COMMENTS_ID = `LOAD_COMMENTS_ID`;
export const LOAD_TREE=`LOAD_TREE`;
export const POST_COMMENT = `POST_COMMENT`;
export const EDIT_COMMENT = `EDIT_COMMENT`;

export const LOAD_HISTORY_ID = `LOAD_HISTORY_ID`;










